// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Noticia {
	
	
	public partial class cadastrar {
		
		protected System.Web.UI.WebControls.Content cadastrarContent;
		
		protected System.Web.UI.HtmlControls.HtmlForm form;
		
		protected System.Web.UI.WebControls.TextBox titulo;
		
		protected System.Web.UI.WebControls.Calendar calendario;
		
		protected System.Web.UI.WebControls.TextBox texto;
		
		protected System.Web.UI.WebControls.Button button;
	}
}
